version: "3"
services:
  bootnode:
    image: parity/parity:v2.7.2-stable
    container_name: bootnode
    volumes:
      - ./bootnode:/home/parity/.local/share/io.parity.ethereum
    command: "--config /home/parity/.local/share/io.parity.ethereum/bootnode.toml"
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
